Ojs\JournalBundle\Entity\ArticleSubmissionFile:
  type: entity
  repositoryClass: Ojs\JournalBundle\Entity\ArticleSubmissionFileRepository
  lifecycleCallbacks: {  }
  manyToOne:
    article:
      targetEntity: Ojs\JournalBundle\Entity\Article
      joinColumn:
        referencedColumnName: id
        name: article_id
      inversedBy: articleSubmissionFiles
