Ojs\JournalBundle\Entity\Article:
  repositoryClass: Ojs\JournalBundle\Entity\ArticleRepository
  table: article
  type: entity
  id:
    id:
      generator:
        strategy: AUTO
      id: true
      type: integer
  lifecycleCallbacks: {}
  manyToOne:
    section:
      targetEntity: Section
      joinColumn:
        name: section_id
        referencedColumnName: id
      inversedBy: articles
    journal:
      targetEntity: Journal
      joinColumn:
        name: journal_id
        referencedColumnName: id
      inversedBy: articles
      fetch: EXTRA_LAZY
    issue:
      targetEntity: Issue
      joinColumn:
        name: issue_id
        referencedColumnName: id
      inversedBy: articles
      fetch: EAGER
    articleType:
      targetEntity: Ojs\JournalBundle\Entity\ArticleTypes
      joinColumn:
        name: article_type_id
        referencedColumnName: id
      fetch: EXTRA_LAZY
    submitterUser:
      targetEntity: Ojs\UserBundle\Entity\User
      joinColumn:
        name: submitter_id
        referencedColumnName: id
  oneToMany:
    attributes:
      targetEntity: ArticleAttribute
      mappedBy: article
      cascade: ["ALL"]
      indexBy: attribute
    articleAuthors:
      targetEntity: ArticleAuthor
      mappedBy: article
      cascade: ["persist"]
    articleFiles:
      targetEntity: ArticleFile
      mappedBy: article
      cascade: ["persist"]
    articleSubmissionFiles:
      targetEntity: Ojs\JournalBundle\Entity\ArticleSubmissionFile
      mappedBy: article
      cascade: ["persist"]
    statistics:
      targetEntity: Ojs\AnalyticsBundle\Entity\ArticleStatistic
      mappedBy: article
      cascade: ["persist"]
  manyToMany:
    languages:
      targetEntity: Lang
      joinTable:
        inverseJoinColumns:
          language_id:
            referencedColumnName: id
        joinColumns:
          article_id:
            referencedColumnName: id
        name: article_language
      fetch: EXTRA_LAZY
    citations:
      targetEntity: Citation
      inversedBy: articles
      joinTable:
        inverseJoinColumns:
          citation_id:
            referencedColumnName: id
        joinColumns:
          article_id:
            referencedColumnName: id
        name: article_citation
      cascade: ["persist"]
  fields:
    titleTransliterated:
      column: title_transliterated
      length: 255
      type: string
      nullable: true
      gedmo:
        - versioned
    primaryLanguage:
      column: primary_language
      type: string
      nullable: true
      gedmo:
        - versioned
    orderNum:
      type: integer
      options:
        default: 0
      nullable: true
      gedmo:
        - versioned
    status:
      type: integer
      options:
        default: 0
      nullable: true
      gedmo:
        - versioned
    setupFinished:
      type: boolean
      options:
        default: 1
      nullable: true
    abstractTransliterated:
      column: abstract_transliterated
      type: text
      nullable: true
      gedmo:
        - versioned
    doi:
      length: 255
      type: string
      nullable: true
      gedmo:
        - versioned
    firstPage:
      column: first_page
      type: integer
      nullable: true
      gedmo:
        - versioned
    anonymous:
      column: is_anonymous
      type: boolean
      nullable: true
      gedmo:
        - versioned
    lastPage:
      column: last_page
      type: integer
      nullable: true
      gedmo:
        - versioned
    otherId:
      column: other_id
      length: 255
      type: string
      nullable: true
      gedmo:
        - versioned
    header:
      type: string
      length: 255
      nullable: true
      gedmo:
        - versioned
    submissionDate:
      column: submission_date
      type: datetime
      nullable: true
    pubdate:
      type: datetime
      nullable: true
      gedmo:
          - versioned
    pubdateSeason:
      column: pubdate_season
      length: 255
      type: string
      nullable: true
    slug:
      type: string
      length: 40
      nullable: true
      gedmo:
        slug:
          seperator: _
          fields:
            - id
    uri:
      length: 255
      type: string
      nullable: true
    note:
      type: text
      nullable: true
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
    deletedAt:
      type: date
      nullable: true
    createdBy:
      type: string
      nullable: true
      gedmo:
        blameable:
          on: create
    updatedBy:
      type: string
      nullable: true
      gedmo:
        blameable:
          on: update
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
    loggable: true
  indexes:
    doix:
      columns: doi
