Ojs\JournalBundle\Entity\JournalFile:
    type: entity
    repositoryClass: Ojs\JournalBundle\Entity\JournalFileRepository
    manyToOne:
        journal:
            targetEntity: Ojs\JournalBundle\Entity\Journal
            joinColumn:
                name: journal_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
