Ojs\JournalBundle\Entity\JournalsIndex:
  type: entity
  table: journals_index
  repositoryClass: Ojs\JournalBundle\Entity\JournalsIndexRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    journalIndexId:
      column: journal_index_id
      type: integer
    link:
      type: text
      gedmo:
          - versioned
  manyToOne:
    journal:
      targetEntity: Ojs\JournalBundle\Entity\Journal
      inversedBy: journalsIndexs
      joinColumn:
        name: journal_id
        referencedColumnName: id
    journalIndex:
      targetEntity: Ojs\JournalBundle\Entity\JournalIndex
      inversedBy: journalsIndexs
      joinColumn:
        name: journal_index_id
        referencedColumnName: id
  gedmo:
      loggable: true
