Ojs\JournalBundle\Entity\JournalIndex:
  type: entity
  repositoryClass: Ojs\JournalBundle\Entity\JournalIndexRepository
  table: journal_indexs
  fields:
    name:
      type: string
      nullable: false
      length: 255
    logo:
      type: string
      length: 255
      nullable: true
    status:
      type: boolean
      gedmo:
          - versioned
  id:
     id:
       generator:
         strategy: AUTO
       id: true
       type: integer
  oneToMany:
    journalsIndexs:
      targetEntity: Ojs\JournalBundle\Entity\JournalsIndex
      mappedBy: journalsIndexs
      cascade: ["all"]
      fetch: EXTRA_LAZY
  gedmo:
      loggable: true
