Ojs\JournalBundle\Entity\PublisherTranslation:
    type: entity
    table: publisher_translations
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        about:
            type: text
            nullable: true

