Ojs\JournalBundle\Entity\SubmissionFile:
    type: entity
    table: submission_file
    repositoryClass: Ojs\JournalBundle\Entity\SubmissionFileRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        article: Ojs\JournalBundle\Entity\ArticleSubmissionFile
        journal: Ojs\JournalBundle\Entity\JournalSubmissionFile
    cache:
        usage: NONSTRICT_READ_WRITE
    id:
      id:
        type: integer
        id: true
        generator:
          strategy: AUTO
    fields:
      title:
        type: string
        gedmo:
            - versioned
      locale:
        type: string
        nullable: true
      detail:
        type: text
        nullable: true
        gedmo:
            - versioned
      visible:
        type: boolean
        nullable: true
      required:
        type: boolean
        nullable: true
      file:
        type: string
        length: 255
        nullable: TRUE
        gedmo:
          - versioned
      deletedAt:
        type: datetime
        nullable: true
    gedmo:
      loggable: true
      soft_deleteable:
        field_name: deletedAt
