language: php

env:
  - SYMFONY_VERSION="2.8.*" DB="mysql"
  - SYMFONY_VERSION="2.8.*" DB="postgres"

php:
  - 5.6
  - 7.0

addons:
  apt_packages:
    - parallel

services:
  - mysql
  - postgresql
  - elasticsearch
  - memcached

sudo: false

before_install:
  - composer self-update
  - npm install -g bower

before_script:
  - composer install --no-interaction --prefer-dist
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer update
  - bower install -f
  - bower update
  - chmod -R 777 app/cache app/logs
  - php app/console assets:install web --symlink --env=dev
  - php app/console assetic:dump
  - php app/console doctrine:database:drop --if-exists --force --env=dev
  - php app/console doctrine:database:create --if-not-exists --env=dev
  - php app/console ojs:install --travis --env=dev
  - php app/console ojs:install:samples --env=dev
  - php app/console h4cc_alice_fixtures:load:sets --env=dev
  - php app/console ojs:normalize:translatable:objects --env=dev
  - php app/console ojs:mail:events:sync --env=dev
  - php app/console ojs:mail:events:sync --sync-desc --env=dev
  - php app/console f:e:p --env=dev

notifications:
  slack: bulutyazilim:8GtvUiq3935dZRc1SObHJVcR#ojs
  email:
    - behramcelen@gmail.com