language: php

env:
  - SYMFONY_VERSION="2.8.*" DB="postgres"

php:
  - 5.6
  - 7.0

addons:
  apt_packages:
    - parallel

services:
  - mysql
  - postgresql
  - elasticsearch
  - memcached

sudo: false

before_install:
  - composer self-update
  - npm install -g bower

before_script:
  - export SYMFONY_ENV=test
  - phpenv config-add travis.php.ini
  - composer install --no-interaction --prefer-dist
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer update
  - bower install --force --silent
  - bower update --force --silent
  - chmod -R 777 app/cache app/logs
  - php app/console assets:install web --symlink --env=test
  - php app/console assetic:dump
  - rm -f app/cache/test/test.db
  - php app/console ojs:install --no-interaction --env=test
  - php app/console ojs:install:samples --env=test
  - php app/console h4cc_alice_fixtures:load:sets --env=test
  - php app/console ojs:normalize:translatable:objects --env=test
  - php app/console ojs:mail:events:sync --env=test
  - php app/console ojs:mail:events:sync --sync-desc --env=test
  - php app/console f:e:p --env=test

script:
  - phpunit -c app src/

notifications:
  slack: bulutyazilim:8GtvUiq3935dZRc1SObHJVcR#ojs
  email:
    - behramcelen+travis@gmail.com