language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
    allow_failures:
        - php: 7.0

env:
    - SYMFONY_VERSION="2.*"
    - MEMCACHED__HOST=localhost

services:
  - mysql
  - elasticsearch
  - memcached

before_script:
# Install php packages
  - memcached -p 11212 -d
  - memcached -p 11213 -d
  - sudo apt-get update > /dev/null
  - sudo apt-get install php5-memcached php5-memcache
  - phpenv config-add config.ini
  - mysql -e 'create database ojs;'
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - composer install --dev --no-interaction --prefer-dist
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php app/console ojs:install:travis
  - npm install -g bower
  - bower install -f
  - chmod -R 777 app/cache app/logs
  - app/console --env=dev cache:warmup
  - php app/console assets:install web --symlink
  - app/console assetic:dump
  - php app/console ojs:setup:samples
 # - mysql ojs < src/Okulbilisim/LocationBundle/Resources/data/location.sql

script: phpunit -c app

notifications:
  slack: okulbilisim:zJjSGCYwjyInYhk1cNFIuyuV
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe449b96442997092a93
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
