ojs_journal_period_index:
    path:     /{journalId}/period/
    defaults: { _controller: "OjsJournalBundle:JournalPeriod:index" }

ojs_journal_period_show:
    path:     /{journalId}/period/{id}/show
    defaults: { _controller: "OjsJournalBundle:JournalPeriod:show" }

ojs_journal_period_new:
    path:     /{journalId}/period/new
    defaults: { _controller: "OjsJournalBundle:JournalPeriod:new" }

ojs_journal_period_create:
    path:     /{journalId}/period/create
    defaults: { _controller: "OjsJournalBundle:JournalPeriod:create" }
    methods: [POST]

ojs_journal_period_edit:
    path:     /{journalId}/period/{id}/edit
    defaults: { _controller: "OjsJournalBundle:JournalPeriod:edit" }

ojs_journal_period_update:
    path:     /{journalId}/period/{id}/update
    defaults: { _controller: "OjsJournalBundle:JournalPeriod:update" }
    methods: [PUT]

ojs_journal_period_delete:
    path:     /{journalId}/period/{id}/delete
    defaults: { _controller: "OjsJournalBundle:JournalPeriod:delete" }
    methods: [DELETE]
