ojs_journal_theme_index:
    path:     /{journalId}/theme/
    defaults: { _controller: "OjsJournalBundle:Theme:index" }

ojs_journal_theme_show:
    path:     /{journalId}/theme/{id}/show
    defaults: { _controller: "OjsJournalBundle:Theme:show" }

ojs_journal_theme_new:
    path:     /{journalId}/theme/new
    defaults: { _controller: "OjsJournalBundle:Theme:new" }

ojs_journal_theme_create:
    path:     /{journalId}/theme/create
    defaults: { _controller: "OjsJournalBundle:Theme:create" }
    methods: [POST]

ojs_journal_theme_edit:
    path:     /{journalId}/theme/{id}/edit
    defaults: { _controller: "OjsJournalBundle:Theme:edit" }

ojs_journal_theme_update:
    path:     /{journalId}/theme/{id}/update
    defaults: { _controller: "OjsJournalBundle:Theme:update" }
    methods: [PUT]

ojs_journal_theme_delete:
    path:     /{journalId}/theme/{id}/delete
    defaults: { _controller: "OjsJournalBundle:Theme:delete" }
    methods: [DELETE]
