Ojs\CmsBundle\Entity\PageTranslation:
  properties:
    title:
      - NotBlank: ~
    body:
      - NotBlank: ~

Ojs\CmsBundle\Entity\Page:
    properties:
        translations:
            - Valid: ~
        tags:
            - NotBlank: ~
