ojs_admin_default_journal_theme_index:
    path:  /
    defaults: { _controller: "OjsAdminBundle:AdminDefaultJournalTheme:index" }

ojs_admin_default_journal_theme_show:
    path:  /{id}/show
    defaults: { _controller: "OjsAdminBundle:AdminDefaultJournalTheme:show" }

ojs_admin_default_journal_theme_new:
    path:  /new
    defaults: { _controller: "OjsAdminBundle:AdminDefaultJournalTheme:new" }

ojs_admin_default_journal_theme_create:
    path:  /create
    defaults: { _controller: "OjsAdminBundle:AdminDefaultJournalTheme:create" }
    methods: [POST]

ojs_admin_default_journal_theme_edit:
    path:  /{id}/edit
    defaults: { _controller: "OjsAdminBundle:AdminDefaultJournalTheme:edit" }

ojs_admin_default_journal_theme_update:
    path:  /{id}/update
    defaults: { _controller: "OjsAdminBundle:AdminDefaultJournalTheme:update" }
    methods:  [PUT]

ojs_admin_default_journal_theme_delete:
    path:  /{id}/delete
    defaults: { _controller: "OjsAdminBundle:AdminDefaultJournalTheme:delete" }
    methods:  [DELETE]
