ojs_admin_institution_managers_index:
    path:  /
    defaults: { _controller: OjsAdminBundle:AdminInstitutionManagers:index }

ojs_admin_institution_managers_show:
    path:  /{id}/show
    defaults: { _controller: OjsAdminBundle:AdminInstitutionManagers:show }

ojs_admin_institution_managers_new:
    path:  /new
    defaults: { _controller: OjsAdminBundle:AdminInstitutionManagers:new }

ojs_admin_institution_managers_create:
    path:  /create
    defaults: { _controller: OjsAdminBundle:AdminInstitutionManagers:create }
    methods: [POST]

ojs_admin_institution_managers_edit:
    path:  /{id}/edit
    defaults: { _controller: OjsAdminBundle:AdminInstitutionManagers:edit }

ojs_admin_institution_managers_update:
    path:  /{id}/update
    defaults: { _controller: OjsAdminBundle:AdminInstitutionManagers:update }
    methods:  [PUT]

ojs_admin_institution_managers_delete:
    path:  /{id}/delete
    defaults: { _controller: OjsAdminBundle:AdminInstitutionManagers:delete }
    methods:  [DELETE]
