Ojs\JournalBundle\Entity\ArticleFile:
    properties:
        type:
            - NotBlank: { groups: [submission] }
        langCode:
            - NotBlank: { groups: [submission] }
        title:
            - NotBlank: { groups: [submission] }
        description:
            - NotBlank: { groups: [submission] }
        file:
            - NotBlank: { groups: [submission] }