Ojs\JournalBundle\Entity\ArticleFile:
    properties:
        type:
            - NotBlank: ~
        langCode:
            - NotBlank: ~
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        file:
            - NotBlank: ~