Ojs\JournalBundle\Entity\ArticleFile:
    properties:
        type:
            - NotBlank: { groups: [submission], message: 'Type fields of article files can not be blank.' }
        langCode:
            - NotBlank: { groups: [submission], message: 'Language fields of article files can not be blank.' }
        title:
            - NotBlank: { groups: [submission], message: 'Title fields of article files can not be blank.' }
        file:
            - NotBlank: { groups: [submission], message: 'File fields of article files can not be blank.' }