Ojs\JournalBundle\Entity\ArticleTranslation:
  properties:
    title:
      - NotBlank: { groups: [submission] }
    subjects:
      - NotBlank: { groups: [submission] }
    subtitle:
      - NotBlank: { groups: [submission] }
    keywords:
      - NotBlank: { groups: [submission] }
    abstract:
      - NotBlank: { groups: [submission] }

Ojs\JournalBundle\Entity\Article:
    properties:
        translations:
            - Valid: ~
        status:
            - NotBlank: ~
        pubdate:
            - NotBlank: ~
        pubdateSeason:
            - NotBlank: ~
        part:
            - NotBlank: ~
        firstPage:
            - NotBlank: ~
        lastPage:
            - NotBlank: ~
        submissionDate:
            - NotBlank: ~
