Ojs\JournalBundle\Entity\ArticleTranslation:
  properties:
    title:
      - NotBlank: { groups: [submission], message: 'Title field for the default language can not be blank.' }
    subjects:
      - NotBlank: { groups: [submission], message: 'Subjects field for the default language can not be blank.' }
    keywords:
      - NotBlank: { groups: [submission], message: 'Keywords field for the default language can not be blank.' }
    abstract:
      - NotBlank: { groups: [submission], message: 'Abstract field for the default language can not be blank.' }

Ojs\JournalBundle\Entity\Article:
    properties:
        translations:
            - Valid: ~
        articleFiles:
            - Valid: ~
        articleAuthors:
            - Valid: ~
        citations:
            - Valid: ~
        status:
            - NotBlank: ~
        pubdate:
            - NotBlank: ~
        part:
            - NotBlank: ~
        firstPage:
            - NotBlank: ~
        lastPage:
            - NotBlank: ~
        submissionDate:
            - NotBlank: ~
