Ojs\JournalBundle\Entity\AuthorTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Author:
    properties:
        translations:
            - Valid: ~
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
