Ojs\JournalBundle\Entity\AuthorTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Author:
    properties:
        translations:
            - Valid: ~
        firstName:
            - NotBlank: { groups: [submission] }
        lastName:
            - NotBlank: { groups: [submission] }
        email:
            - NotBlank: { groups: [submission] }
            - Email: { groups: [submission] }
