Ojs\JournalBundle\Entity\Citation:
    properties:
        raw:
            - NotBlank: { groups: [submission] }
        type:
            - NotBlank: { groups: [submission] }
        orderNum:
            - NotBlank: { groups: [submission] }