Ojs\JournalBundle\Entity\ContactTypesTranslation:
  properties:
    name:
      - NotBlank: ~
    description:
      - NotBlank: ~

Ojs\JournalBundle\Entity\ContactTypes:
    properties:
        translations:
            - Valid: ~
