Ojs\JournalBundle\Entity\IssueTranslation:
  properties:
    title:
      - NotBlank: ~
    description:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Issue:
    properties:
        translations:
            - Valid: ~
        volume:
            - NotBlank: ~
        number:
            - NotBlank: ~
        datePublished:
            - NotBlank: ~
        tags:
            - NotBlank: ~
        year:
            - NotBlank: ~
        full_file:
            - NotBlank: ~
