Ojs\JournalBundle\Entity\IssueTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Issue:
    properties:
        translations:
            - Valid: ~
        year:
            - NotBlank: ~
