Ojs\JournalBundle\Entity\JournalTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Journal:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: issn
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: eissn
    properties:
        translations:
            - Valid: ~
        mandatoryLang:
            - NotBlank: ~
        languages:
            - NotBlank: ~
        issn:
            - Issn: ~
        eissn:
            - Issn: ~
        founded:
            - NotBlank: ~
