Ojs\JournalBundle\Entity\JournalTranslation:
  properties:
    title:
      - NotBlank: ~
    subtitle:
      - NotBlank: ~
    description:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Journal:
    properties:
        translations:
            - Valid: ~
        mandatoryLang:
            - NotBlank: ~
        languages:
            - NotBlank: ~
        issn:
            - Issn: ~
        eissn:
            - Issn: ~
        firstPublishDate:
            - NotBlank: ~
        status:
            - NotBlank: ~
