Ojs\JournalBundle\Entity\JournalTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\Journal:
    properties:
        translations:
            - Valid: ~
        mandatoryLang:
            - NotBlank: ~
        languages:
            - NotBlank: ~
        issn:
            - Issn: ~
        eissn:
            - Issn: ~
        founded:
            - NotBlank: ~
