Ojs\JournalBundle\Entity\JournalContactTranslation:
  properties:
    title:
      - NotBlank: ~

Ojs\JournalBundle\Entity\JournalContact:
    properties:
        translations:
            - Valid: ~
        fullName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        tags:
            - NotBlank: ~
        contactType:
            - NotBlank: { groups: [admin] }
        journal:
            - NotBlank: { groups: [admin] }
