imports:
    - { resource: config_dev.yml }

parameters:
    doctrine.dbal.connection_factory.class: Liuggio\Fastest\Doctrine\DBAL\ConnectionFactory

framework:
    test: ~
    default_locale: "%locale%"
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    transport:  mail
    # (smtp, mail, sendmail, or gmail)
    spool:
        type: "file" #(how to queue the messages, file or memory is supported, see How to Spool Emails)
        path: "%kernel.root_dir%/spool" #(where to store the messages)
    #delivery_address: (an email address where to send ALL emails)
    #disable_delivery: (set to true to disable delivery completely)

liip_functional_test: ~

security:
    firewalls:
        main:
            http_basic: ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
<<<<<<< HEAD
                path:     '%kernel.cache_dir%/test.db'
=======
                path:     '%kernel.cache_dir%/__DBNAME__.db'
>>>>>>> origin/iss1517
