imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: ojs_params.yml }
  - { resource: bibliography_params.yml }
  - { resource: services.yml }
  - { resource: assetic.yml }
  - { resource: doctrine.yml }
  - { resource: elastica.yml }
  - { resource: api.yml }
  - { resource: swift.yml }
  - { resource: media.yml }

parameters:
  admin_base_view: '::ojsbase.html.twig'

framework:
  translator:      { fallback: %locale% }
  secret:          "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  templating:
     { engines: ['twig'] }
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
    handler_id:  ~
    cookie_domain: ".%base_host%"
  fragments:       ~
  http_method_override: true
  validation:    { enabled: true}

# Twig Configuration
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  form:
    resources:
      - '::uploadfields.html.twig'
      - 'BraincraftedBootstrapBundle:Form:bootstrap.html.twig'
      - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
      - 'OjsCoreBundle:Form:fields.html.twig'
  globals:
    languages : "%languages%"
    base_host: %base_host%
    admin_base_view: %admin_base_view%
    https: %https%
    ojs_logo: %ojs_logo%
    ojs_tw: %ojs_tw%
    ojs_fb: %ojs_fb%
    project_name: %project_name%
  number_format:
    decimals: 0
    decimal_point: ','
    thousands_separator: '.'

fos_rest:
  body_listener: true
  format_listener: true
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      xml: true
      json : true
    templating_formats:
      html: true
    force_redirects:
      html: true
    failed_validation: HTTP_BAD_REQUEST
    default_engine: twig
  routing_loader:
    default_format: json

sensio_framework_extra:
  view:
    annotations: false

stof_doctrine_extensions:
  default_locale: "%locale%"
  translation_fallback: true
  orm:
    default:
      timestampable: true
      translatable: true
      blameable: true
      loggable: true
      uploadable: true
      sluggable: true
      tree: true
jms_di_extra:
  disable_grep: true
nelmio_api_doc: ~

knp_paginator:
  page_range: 5                      # default page range used in pagination control
  default_options:
    page_name: page                # page query parameter name
    sort_field_name: sort          # sort field query parameter name
    sort_direction_name: direction # sort direction query parameter name
    distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
  template:
    pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
    sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
apy_data_grid:
  theme: '::list.html.twig'

jms_di_extra:
  locations:
    all_bundles: false
    bundles: [OjsJournalBundle]
    directories: ["%kernel.root_dir%/../src"]

sc_datetimepicker:
  picker: ~

a2lix_translation_form:
    locale_provider: default
    locales: %locale_support%
    default_locale: %locale%
    required_locales: [%locale%]
    manager_registry: doctrine
    templating: "::translation_form.html.twig"

fos_user:
  db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
  firewall_name: main
  user_class: Ojs\UserBundle\Entity\User
  registration:
    form:
      type: ojs_user_register
  registration:
    confirmation:
      enabled: true
      from_email:
        address: %system_email%
        sender_name: %project_name%
  service:
    mailer: fos_user.mailer.twig_swift
    user_manager: ojs_user.manager

knp_menu:
    twig:
        template: ::menu.html.twig

prezent_doctrine_translatable:
    fallback_locale: %locale%

jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs, vendor]
            extractors: [alias_of_the_extractor]
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "@OjsUserBundle/Resources/config/serializer/FOSUB"
presta_sitemap:
    timetolive: 3600
    dumper_base_url: "http://%base_host%/"
    route_annotation_listener: false
    items_by_set: 50000
hwi_oauth:
  connect:
    account_connector: ojs.user.oauth
  firewall_name: main
  resource_owners:
    orcid:
      type:                oauth2
      client_id:           %orcid.client_id%
      client_secret:       %orcid.client_secret%
      access_token_url:    https://pub.orcid.org/oauth/token
      authorization_url:   https://orcid.org/oauth/authorize
      infos_url:           http://pub.orcid.org/v1.2
      scope:               "/authenticate"
      user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
      paths:
        identifier: "orcid-profile.orcid-identifier.path"
        nickname: "orcid-profile.orcid-identifier.path"
        lastname:   "orcid-profile.orcid-bio.personal-details.family-name.value"
        firstname:   "orcid-profile.orcid-bio.personal-details.given-names.value"
        realname:   "orcid-profile.orcid-bio.personal-details.family-name.value"
    linkedin:
      type:           linkedin
      client_id:      %linkedin.client_id%
      client_secret:  %linkedin.client_secret%
      scope:          r_emailaddress
