Ojs\JournalBundle\Entity\ArticleTypes:
  checkUse:
    - { entityName: 'OjsJournalBundle:Article', field: articleType}

Ojs\JournalBundle\Entity\PersonTitle:
  checkUse:
    - { entityName: 'OjsJournalBundle:JournalContact', field: title}

Ojs\JournalBundle\Entity\PublisherTheme:
  checkUse:
    - { entityName: 'OjsJournalBundle:Publisher', field: theme}

Ojs\JournalBundle\Entity\PublisherDesign:
  checkUse:
    - { entityName: 'OjsJournalBundle:Publisher', field: design}

Ojs\JournalBundle\Entity\Index:
  checkUse:
    - { entityName: 'OjsJournalBundle:JournalIndex', field: index}

Ojs\JournalBundle\Entity\PublisherTypes:
  checkUse:
    - { entityName: 'OjsJournalBundle:Publisher', field: publisherType}
    - { entityName: 'OjsJournalBundle:Institution', field: institutionType}

Ojs\JournalBundle\Entity\JournalTheme:
  checkUse:
    - { entityName: 'OjsJournalBundle:Journal', field: theme}

Ojs\JournalBundle\Entity\ContactTypes:
  checkUse:
    - { entityName: 'OjsJournalBundle:JournalContact', field: contactType}

Ojs\JournalBundle\Entity\Board:
  checkUse:
    - { entityName: 'OjsJournalBundle:BoardMember', field: board}

Ojs\JournalBundle\Entity\Lang:
  checkUse:
    - { entityName: 'OjsJournalBundle:Journal', field: mandatoryLang}
    - { entityName: 'OjsJournalBundle:Journal', field: languages, type: m2m}
    - { entityName: 'OjsJournalBundle:Article', field: languages, type: m2m}
