Ojs\JournalBundle\Entity\ArticleTypes:
  checkUse:
    'OjsJournalBundle:Article':
      field: articleType

Ojs\JournalBundle\Entity\PersonTitle:
  checkUse:
    'OjsJournalBundle:JournalContact':
      field: title

Ojs\JournalBundle\Entity\PublisherTheme:
  checkUse:
    'OjsJournalBundle:Publisher':
      field: theme

Ojs\JournalBundle\Entity\Index:
  checkUse:
    'OjsJournalBundle:JournalIndex':
      field: index

Ojs\JournalBundle\Entity\PublisherTypes:
  checkUse:
    'OjsJournalBundle:Publisher':
      field: publisherType
    'OjsJournalBundle:Institution':
      field: institutionType