parameters:
  fos_elastica.client.class: Ojs\CoreBundle\Service\ElasticaClient
fos_elastica:
  clients:
    #you can change to your setting
    default: { host: %elasticsearch_host%, port: 9200 , logger: false}
  indexes:
    search:
      index_name: %base_host%
      settings:
        analysis:
          analyzer:
            stopwords:
              type: standard
              stopwords: [ "and", "of", "the", "ve", "veya", "or", "ile", "da", "de", "mı", "mi" ]
      finder: ~
      client: default
      types:
        user:
          indexable_callback: 'isIndexable'
          mappings:
            title:
              type: "object"
              properties:
                title:
                  type: string
            username:
              type: string
            firstName:
              type: string
              fields:
                raw:
                  type: string
                  index: not_analyzed
            lastName:
              type: string
            email:
              type: string
            avatar:
              type: string
            tags:
              analyzer: "keyword"
              type: string
            subjects: {"index": "not_analyzed"}
            gender: {"index": "not_analyzed"}
            created:
              type: date
            updated:
              type: date
            journalUsers:
              type: object
              properties:
                journal:
                  type: object
                  properties:
                    title:
                      type: string
                      index: not_analyzed
                    id:
                      type: integer
                      index: not_analyzed
                roles:
                  index: not_analyzed
                  type: string
          persistence:
            driver: orm
            model: Ojs\UserBundle\Entity\User
            provider: ~
            listener: ~
            finder: ~
            provider:
              debug_logging: true
        articles:
          indexable_callback: 'isIndexable'
          mappings:
            translations:
              type: "object"
              properties:
                locale:
                  type: string
                title:
                  type: string
                keywords:
                  type: string
                abstract:
                  type: string
            subjects:
              type: object
              properties:
                id: { type: integer }
                subject: { type: string, index: not_analyzed }
            status:
              type: string
              index: not_analyzed
            keywords: { type: string, boost: 4}
            title: { type: string, boost: 5 }
            locale:
              type: string
              index: not_analyzed
            citations:
              type: "object"
              properties:
                raw: { boost: 2 ,type: string}
                id:  { boost: 1 ,type: integer}
            articleAuthors:
              type: "object"
              properties:
                author:
                  type: "object"
                  properties:
                    id:
                      type: integer
                    firstName:
                      type: string
                    lastName:
                      type: string
                    middleName:
                      type: string
                    email:
                      type: string
                    tags:
                      analyzer: "keyword"
                      type: string
            attributes:
              type: "object"
              properties:
                value:
                  type: string
            journal:
              type: "object"
              properties:
                id:
                  index: not_analyzed
                slug:
                  type: string
                publisher:
                  type: object
                  properties:
                    slug:
                      type: string
            issue:
              type: "object"
              properties:
                id:
                  type: integer
                  index: not_analyzed
            section:
              type: "object"
              properties:
                title:
                  type: string
                  index: not_analyzed
          persistence:
            driver: orm
            model: Ojs\JournalBundle\Entity\Article
            provider: ~
            listener:
            finder: ~
            provider:
              debug_logging: false
        publisher:
          indexable_callback: 'isIndexable'
          mappings:
            translations:
              type: "object"
              properties:
                about:
                  type: string
            tags:
              analyzer: "keyword"
              type: string
            name:
              type: string
              fields:
                raw:
                  type: string
                  index: not_analyzed
            slug:
              type: string
            verified:
              type: boolean
            publisherType:
              type: object
              properties:
                name: { index: not_analyzed }
            url:
              type: string
            logo:
              type: string
          persistence:
            driver: orm
            model: Ojs\JournalBundle\Entity\Publisher
            provider: ~
            listener: ~
            finder: ~
            provider:
              debug_logging: false
        journal:
          mappings:
            id: { type: integer }
            translations:
              type: "object"
              properties:
                locale:
                  type: string
                title:
                  type: string
                subtitle:
                  type: string
                description:
                  type: string
                titleAbbr:
                  type: string
            title:
              type: string
              fields:
                raw:
                  type: string
                  index: not_analyzed
            slug: { type: string }
            subtitle: { type: string }
            description: { type: string }
            issn: { type: string }
            eissn: { type: string }
            founded: { type: date }
            tags:
              analyzer: "keyword"
              type: string
            status: { "index": "not_analyzed" }
            accessModal: { type: integer }
            subjects:
              type: object
              properties:
                id: { type: integer }
                subject: { type: string, index: not_analyzed }
            publisher:
              type: object
              properties:
                name:
                  type: string
                  fields:
                    raw:
                      type: string
                      index: not_analyzed
                slug: { type: string }
                publisherType:
                  type: object
                  properties:
                    name: { index: not_analyzed }
            periods:
              type: object
              properties:
                period: { type: string }
            image: ~
            viewCount: {type: integer}
            downloadCount: {type: integer}
            journalIndexs:
              type: object
              properties:
                index:
                  type: object
                  properties:
                    name:
                      type: string
                      fields:
                        raw:
                          type: string
                          index: not_analyzed
            mandatoryLang: {index: not_analyzed}
          persistence:
            driver: orm
            model: Ojs\JournalBundle\Entity\Journal
            provider: ~
            listener: ~
            finder: ~
            provider:
              debug_logging: false
        subject:
          mappings:
            translations:
              type: "object"
              properties:
                subject:
                  type: string
                description:
                  type: string
            subject:
              type: string
              fields:
                raw:
                  type: string
                  index: not_analyzed
            tags:
              analyzer: "keyword"
              type: string
          persistence:
            driver: orm
            model: Ojs\JournalBundle\Entity\Subject
            provider: ~
            listener: ~
            finder: ~
            provider:
              debug_logging: false
        country:
          mappings:
            name:
              type: string
          persistence:
            driver: orm
            model: BulutYazilim\LocationBundle\Entity\Country
            provider: ~
            listener: ~
            finder: ~
            provider:
              debug_logging: false
        citation:
          mappings:
            raw:
              type: string
            type:
              type: string
            articles:
              type: "object"
              properties:
                id:  { boost: 1 ,type: integer}
                journal:
                  type: "object"
                  properties:
                    slug: { boost: 1 ,type: string}
                    publisher:
                      type: "object"
                      properties:
                        slug: { boost: 1 ,type: string}
          persistence:
            driver: orm
            model: Ojs\JournalBundle\Entity\Citation
            provider: ~
            listener: ~
            finder: ~
        journal_page:
          mappings:
            id:
              type: integer
            title:
              type: string
            tags:
              analyzer: "keyword"
              type: string
          persistence:
            driver: orm
            model: Ojs\JournalBundle\Entity\JournalPage
            provider: ~
            listener: ~
            finder: ~
        author:
          mappings:
            title:
              type: "object"
              properties:
                title:
                  type: string
            id:
              type: integer
            translations:
              type: "object"
              properties:
                biography:
                  type: string
            firstName:
              type: string
            lastName:
              type: string
            middleName:
              type: string
            email:
              type: string
            tags:
              analyzer: "keyword"
              type: string
            articleAuthors:
              type: object
              properties:
                article:
                  type: object
                  properties:
                    id:
                      type: integer
                    issue:
                      type: "object"
                      properties:
                        id:
                          type: integer
                    journal:
                      type: object
                      properties:
                        id:
                          type: integer
                        slug:
                          type: string
                        publisher:
                          type: object
                          properties:
                            slug:
                              type: string
          persistence:
            driver: orm
            model: Ojs\JournalBundle\Entity\Author
            provider: ~
            listener: ~
            finder: ~
