app_extra:
  resource: .
  type: advanced_extra
journal_publisher_hosting:
  prefix: /
  resource: '@OjsSiteBundle/Resources/config/routing/hosting.yml'
  condition: 'not (context.getHost() matches "/%base_host%/")'
ojs_admin:
  resource: '@OjsAdminBundle/Resources/config/routing.yml'
  prefix: admin
ojs_admin_root:
  resource: '@OjsAdminBundle/Resources/config/routing_root.yml'
ojs_installer:
  resource: '@OjsInstallerBundle/Resources/config/routing.yml'
ojs_oai:
  resource: '@OjsOAIBundle/Resources/config/routing.yml'
  prefix: /api/public/oai
ojs_search:
  resource: '@OjsSearchBundle/Resources/config/routing.yml'
ojs_journal:
  resource: '@OjsJournalBundle/Resources/config/routing.yml'
ojs_journal_panel:
  resource: '@OjsJournalBundle/Resources/config/routing_panel.yml'
  prefix: /journal
auth:
  resource: '@OjsUserBundle/Resources/config/routing.yml'
ojs_user:
  resource: '@OjsUserBundle/Controller/'
  type: annotation
ojs_location:
  resource: '@OjsLocationBundle/Resources/config/routing.yml'
rest:
  type: rest
  resource: routing_rest.yml
  prefix: /api/
feedback:
  resource: '@OkulbilisimFeedbackBundle/Resources/config/routing.yml'
oneup_uploader:
  resource: .
  type: uploader
_liip_imagine:
  resource: '@LiipImagineBundle/Resources/config/routing.xml'
change_locale:
  path: '/locale/{code}'
  defaults:
    _controller: 'OjsJournalBundle:Common:changeLocale'
apidoc:
  resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
  prefix: /api/public/doc
fos_js_routing:
  resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'
jb_fileupload_crop:
  resource: '@JbFileUploaderBundle/Resources/config/routing.yml'
ojs_site:
  resource: '@OjsSiteBundle/Resources/config/routing.yml'
fos_user:
  resource: '@FOSUserBundle/Resources/config/routing/all.xml'
