ojs_api_doc:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /public/v1/doc

ojs_api_home:
    resource: "@OjsApiBundle/Resources/config/routing.yml"
    prefix:   /
    
ojs_rest: 
  type: rest
  resource: "@OjsApiBundle/Resources/config/routing_rest.yml"