services:
  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  ojs.ojs_mailer:
    class: Ojs\UserBundle\Service\MailerService
    arguments: [@mailer, @templating, @doctrine.orm.entity_manager, "%system_email%"]

  gedmo.listener.softdeleteable:
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ @annotation_reader ] ]

  api_key_user_provider:
    class: Ojs\ApiBundle\Security\ApiKeyUserProvider
    arguments: ["@doctrine.orm.default_entity_manager"]

  apikey_authenticator:
    class:   Ojs\ApiBundle\Security\ApiKeyAuthenticator
    arguments: ["@api_key_user_provider"]

  ojs_search_manager:
    class: Ojs\SearchBundle\Manager\SearchManager
    arguments: [@translator,@router]

  ojs.twig.common_extension:
    class: Ojs\SiteBundle\Twig\CommonExtension
    arguments: [@doctrine.orm.entity_manager, @liip_imagine.filter.manager]
    tags:
      - {name: twig.extension }

  ojs.user_provider.username_email:
    class: Ojs\UserBundle\Service\EmailUserProvider
    arguments: [@doctrine.orm.entity_manager]

  form.type.journal_user:
    class: Ojs\JournalBundle\Form\Type\JournalUserType
    tags:
      - { name: form.type, alias: ojs_journalbundle_journaluser }

  form.type.users_type:
    class: Ojs\UserBundle\Form\Type\UsersFieldType
    arguments: [ @doctrine.orm.entity_manager, @router, "2", "10" ]
    tags:
        - { name: form.type, alias: users_type }

  kernel.listener.command_dispatch:
    class: Ojs\CliBundle\EventListener\ConsoleExceptionListener
    arguments:
      logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: console.exception }

  analytics.listener:
    class: Ojs\AnalyticsBundle\Listener\AnalyticsSubscriber
    arguments:
      - @doctrine.orm.entity_manager
    tags:
      - { name: kernel.event_subscriber }
