services:
  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  ojs_locale.locale_listener:
    class: Ojs\Common\Services\LocaleListener
    arguments: ["%kernel.default_locale%"]
    tags:
      - { name: kernel.event_subscriber }

  ojs.twig.ojs_extension:
    class: Ojs\Common\Twig\OjsExtension
    arguments:
      - @doctrine.orm.entity_manager
      - @router
      - @translator
      - @ojs.journal_service
      - @user.helper
      - @security.token_storage
      - @session
      - "%cms_show_routes%"
      - "%defaultInstitutionSlug%"
      - "%ojs_logo%"
      - "%ojs_tw%"
      - "%ojs_fb%"
    tags:
      - { name: twig.extension }


  ojs.twig.history_extension:
    class: Ojs\Common\Twig\HistoryExtension
    arguments:
      - @doctrine.orm.entity_manager
      - @twig
      - "::_history.html.twig"
    tags:
      - { name: twig.extension }

  ojs.twig.action_extension:
    class: Ojs\Common\Twig\ActionExtension
    arguments:
      - @translator
    tags:
      - { name: twig.extension }

  ojs.security_switch_user:
    class: Ojs\Common\Services\SecuritySwitchUserListener
    arguments: [@security.token_storage]
    tags:
      - { name: kernel.event_listener, event: security.switch_user, method: onSecuritySwitchUser }

  ojs.ojs_mailer:
    class: Ojs\UserBundle\Service\MailerService
    arguments: [@mailer, @templating, @doctrine.orm.entity_manager, "%system_email%"]

  gedmo.listener.softdeleteable:
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ @annotation_reader ] ]

  api_key_user_provider:
    class: Ojs\ApiBundle\Security\ApiKeyUserProvider
    arguments: ["@doctrine.orm.default_entity_manager"]

  apikey_authenticator:
    class:   Ojs\ApiBundle\Security\ApiKeyAuthenticator
    arguments: ["@api_key_user_provider"]

  ojs_search_manager:
    class: Ojs\SearchBundle\Manager\SearchManager
    arguments: [@translator,@router]

  ojs.twig.common_extension:
    class: Ojs\SiteBundle\Twig\CommonExtension
    arguments: [@doctrine.orm.entity_manager, @liip_imagine.filter.manager]
    tags:
      - {name: twig.extension }

  ojs.user_provider.username_email:
    class: Ojs\UserBundle\Service\EmailUserProvider
    arguments: [@doctrine.orm.entity_manager]

  ojs.journal_service:
    class: Ojs\Common\Services\JournalService
    arguments:
      - @doctrine.orm.entity_manager
      - @session
      - @router
      - @security.token_storage
      - @request_stack
      - "%defaultInstitutionSlug%"
      - "%ojs_logo%"
      - "%ojs_tw%"
      - "%ojs_fb%"

  ojs.article_service:
    class: Ojs\Common\Services\ArticleService
    arguments: [ @doctrine.orm.entity_manager, @ojs.journal_service, @session ]

  ojs.alice.provider:
    class: Ojs\Common\Services\AliceDataProvider
    arguments: [ "%defaultInstitutionSlug%", "%system_email%" ]
    tags:
      -  { name: h4cc_alice_fixtures.provider }

  user.helper:
    class: Ojs\Common\Services\UserListener
    arguments:
      - @router
      - @doctrine.orm.entity_manager
      - "%kernel.root_dir%"
      - @ojs.journal_service
      - @security.encoder_factory
      - @security.authorization_checker
      - @security.token_storage

  grid_action:
    class: Ojs\Common\Services\GridAction
    arguments: [@security.csrf.token_manager, @translator, @ojs.cms.twig.post_extension]

  form.type.entity:
    class: Ojs\Common\Form\Type\EntityType
    arguments: [@doctrine]
    tags:
      - { name: form.type, alias: entity }

  form.type.tags:
    class: Ojs\Common\Form\Type\TagsType
    arguments: [ @router, @translator ]
    tags:
      - { name: form.type, alias: tags }

  form.type.journal_user:
    class: Ojs\JournalBundle\Form\Type\JournalUserType
    tags:
      - { name: form.type, alias: ojs_journalbundle_journaluser }

  form.type.users_type:
    class: Ojs\UserBundle\Form\Type\UsersFieldType
    arguments: [ @doctrine.orm.entity_manager, @router, "2", "10" ]
    tags:
        - { name: form.type, alias: users_type }

  kernel.listener.command_dispatch:
    class: Ojs\CliBundle\EventListener\ConsoleExceptionListener
    arguments:
      logger: "@logger"
    tags:
      - { name: kernel.event_listener, event: console.exception }

  analytics.listener:
    class: Ojs\AnalyticsBundle\Listener\AnalyticsSubscriber
    arguments:
      - @doctrine.orm.entity_manager
    tags:
      - { name: kernel.event_subscriber }
