ojs_institution_manager_design_index:
    path:  /
    defaults: { _controller: OjsJournalBundle:ManagerInstitutionDesign:index }

ojs_institution_manager_design_show:
    path:  /{id}/show
    defaults: { _controller: OjsJournalBundle:ManagerInstitutionDesign:show }

ojs_institution_manager_design_new:
    path:  /new
    defaults: { _controller: OjsJournalBundle:ManagerInstitutionDesign:new }

ojs_institution_manager_design_create:
    path:  /create
    defaults: { _controller: OjsJournalBundle:ManagerInstitutionDesign:create }
    methods: [POST]

ojs_institution_manager_design_edit:
    path:  /{id}/edit
    defaults: { _controller: OjsJournalBundle:ManagerInstitutionDesign:edit }

ojs_institution_manager_design_update:
    path:  /{id}/update
    defaults: { _controller: OjsJournalBundle:ManagerInstitutionDesign:update }
    methods:  [PUT]

ojs_institution_manager_design_delete:
    path:  /{id}/delete
    defaults: { _controller: OjsJournalBundle:ManagerInstitutionDesign:delete }
    methods:  [DELETE]
