institution_theme:
    resource: "@OjsJournalBundle/Resources/config/routing/institution/theme.yml"
    prefix:   /theme

institution_design:
    resource: "@OjsJournalBundle/Resources/config/routing/institution/design.yml"
    prefix:   /design