ojs_institution_manager_edit:
    path:  /edit
    defaults: { _controller: OjsJournalBundle:ManagerInstitution:edit }

ojs_institution_manager_update:
    path:  /update
    defaults: { _controller: OjsJournalBundle:ManagerInstitution:update }
    methods:  [PUT]

institution_theme:
    resource: "@OjsJournalBundle/Resources/config/routing/institution/theme.yml"
    prefix:   /theme

institution_design:
    resource: "@OjsJournalBundle/Resources/config/routing/institution/design.yml"
    prefix:   /design