proxy:
    resource: "@OjsUserBundle/Resources/config/routing/proxy.yml"
    prefix:   /manager/proxy


admin_notification:
    resource: "@OjsUserBundle/Resources/config/routing/notification_admin.yml"
    prefix:   /admin/notification

user:
    resource: "@OjsUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

confirm_email_warning:
    path:  /unconfirmed
    defaults: { _controller: "OjsUserBundle:Security:unconfirmed" }

login:
    path: /login
    host: "%base_host%"
    defaults: { _controller: OjsUserBundle:Security:login }

orcid_login:
    path: /orcid_login
    defaults: { _controller: OjsUserBundle:Orcid:login }

email_confirm:
    path: /confirm/email/{code}
    defaults: { _controller: OjsUserBundle:Security:confirmEmail }

logout:
    path: /logout

login_check:
    path: /login_check

regenerate_apikey:
    path: /user/apikey/regenerate
    defaults: { _controller: OjsUserBundle:Security:regenerateAPI }

user_create_password:
    path: /password/create
    defaults: { _controller: "OjsUserBundle:Security:createPassword" }
