Ojs\UserBundle\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
  properties:
    username:
      - NotBlank: { groups: [ojs_register,editProfile] }
    password:
      - NotBlank: { groups: [ojs_register] }
      - Length: { min: 6, groups: [ojs_register] }
    email:
      - NotBlank: { groups: [ojs_register,editProfile] }
      - Email: { groups: [ojs_register,editProfile] }
    extraEmails:
      - Ojs\UserBundle\Validator\Constraints\UniqueEmails: { message: 'user.extra_emails.invalid' }
    firstName:
      - NotBlank: { groups: [ojs_register, editProfile] }
    lastName:
      - NotBlank: { groups: [ojs_register] }
