Ojs\UserBundle\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
  properties:
    username:
      - NotBlank: { groups: [ojs_register,editProfile] }
    password:
      - NotBlank: { groups: [Default, editProfile] }
      - Length: { min: 6, groups: [Default, editProfile] }
    plainPassword:
      - NotBlank: { groups: [ojs_register] }
      - Length: { min: 6, groups: [ojs_register] }
    email:
      - NotBlank: { groups: [ojs_register,editProfile] }
      - Email: { groups: [ojs_register,editProfile] }
      - Ojs\UserBundle\Validator\Constraints\UniqueMultipleEmails: { message: 'user.multiple_mail.invalid', groups: [ojs_register,editProfile]}
    firstName:
      - NotBlank: { groups: [ojs_register, editProfile] }
    lastName:
      - NotBlank: { groups: [ojs_register] }
