Ojs\UserBundle\Entity\User:
  properties:
    username:
      - NotBlank: { groups: [ojs_register] }
    password:
      - NotBlank: { groups: [ojs_register] }
      - Length: { min: 6, groups: [ojs_register] }
    email:
      - NotBlank: { groups: [ojs_register] }
      - Email: { groups: [ojs_register] }
    firstName:
      - NotBlank: { groups: [ojs_register] }
    lastName:
      - NotBlank: { groups: [ojs_register] }
