Ojs\SiteBundle\Entity\BlockTranslation:
  type: entity
  table: blocks_translations
  id:
      id:
          type: integer
          id: true
          generator:
              strategy: AUTO
  fields:
      title:
          type: string
          length: 255
      content:
          type: text
          nullable: TRUE