Ojs\SiteBundle\Entity\Block:
  type: entity
  table: blocks
  repositoryClass: Ojs\SiteBundle\Entity\BlockRepository
  cache:
      usage: NONSTRICT_READ_WRITE
  oneToMany:
    links:
      targetEntity: Ojs\SiteBundle\Entity\BlockLink
      mappedBy: block
      cascade: ["persist", "remove"]
      fetch: EXTRA_LAZY
      orderBy: { link_order: 'asc' }
      cache:
          usage: NONSTRICT_READ_WRITE
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    objectType:
      type: string
      column: object_type
    objectId:
      type: integer
      column: object_id
    type:
      type: string
    color:
      type: string
      nullable: true
    block_order:
      type: integer
      nullable: true
