services:
  ojs.journal_service:
    class: Ojs\JournalBundle\Service\JournalService
    arguments:
      - @doctrine.orm.entity_manager
      - @session
      - @router
      - @security.token_storage
      - @request_stack
      - "%defaultPublisherSlug%"
  journal.orm_event_listener:
    class: Ojs\JournalBundle\Listeners\AclOrmListener
    arguments: [@service_container]
    tags:
        - { name: doctrine.event_listener, event: postPersist }

  form.type.journal_users_type:
    class: Ojs\JournalBundle\Form\Type\JournalUsersFieldType
    arguments: [@ojs.journal_service]
    tags:
        - { name: form.type, alias: journal_users_type }

  ojs.serializationlistener:
    class: Ojs\CoreBundle\Listeners\SerializationListener
    arguments: []
    tags:
        - { name: jms_serializer.event_subscriber }