api_contact_types:
  type:         rest
  resource:     "OjsApiBundle:ContactTypesRest"
  prefix:       /v1
  name_prefix:  api_1_

api_journal:
  type:         rest
  resource:     "OjsApiBundle:JournalRest"
  prefix:       /v1
  name_prefix:  api_1_

api_publisher:
  type:         rest
  resource:     "OjsApiBundle:PublisherRest"
  prefix:       /v1
  name_prefix:  api_1_

api_institution:
  type:         rest
  resource:     "OjsApiBundle:InstitutionRest"
  prefix:       /v1
  name_prefix:  api_1_

api_subject:
  type:         rest
  resource:     "OjsApiBundle:SubjectRest"
  prefix:       /v1
  name_prefix:  api_1_

api_lang:
  type:         rest
  resource:     "OjsApiBundle:LangRest"
  prefix:       /v1
  name_prefix:  api_1_

api_index:
  type:         rest
  resource:     "OjsApiBundle:IndexRest"
  prefix:       /v1
  name_prefix:  api_1_

api_period:
  type:         rest
  resource:     "OjsApiBundle:PeriodRest"
  prefix:       /v1
  name_prefix:  api_1_

api_person_title:
  type:         rest
  resource:     "OjsApiBundle:PersonTitleRest"
  prefix:       /v1
  name_prefix:  api_1_

api_publisher_type:
  type:         rest
  resource:     "OjsApiBundle:PublisherTypeRest"
  prefix:       /v1
  name_prefix:  api_1_

api_article_type:
  type:         rest
  resource:     "OjsApiBundle:ArticleTypeRest"
  prefix:       /v1
  name_prefix:  api_1_

api_contact:
  type:         rest
  resource:     "OjsApiBundle:ContactRest"
  prefix:       /v1
  name_prefix:  api_1_

api_authors:
  type: rest
  resource:     "OjsApiBundle:AuthorRest"
  name_prefix:  api_

api_users:
  type: rest
  resource:     "OjsApiBundle:UserRest"
  name_prefix:  api_

api_issues:
  type: rest
  resource:     "OjsApiBundle:IssueRest"
  name_prefix:  api_

api_test :
  type: rest
  resource:     "OjsApiBundle:TestRest"
  name_prefix:  api_

api_roles :
  type: rest
  resource:     "OjsApiBundle:RoleRest"
  name_prefix:  api_

api_article :
  type: rest
  resource:     "OjsApiBundle:ArticleRest"
  name_prefix:  api_

api_analytics :
  type: rest
  resource:     "OjsApiBundle:AnalyticsRest"
  name_prefix:  api_

api_mail_templates :
  type: rest
  resource:     "OjsApiBundle:MailTemplateRest"
  name_prefix:  api_

api_public_search :
  type: rest
  resource:     "OjsApiBundle:PublicSearchRest"
  name_prefix:  api_

api_search:
    type: rest
    resource: "OjsApiBundle:SearchRest"
    name_preffix: api_

api_public_user:
    type: rest
    resource: "OjsApiBundle:PublicUserRest"
    name_preffix: api_
