parameters:
    ojs_api.contact_type.handler.class: Ojs\ApiBundle\Handler\ContactTypesHandler
    ojs_api.contact_type.class: Ojs\JournalBundle\Entity\ContactTypes
    ojs_api.journal.handler.class: Ojs\ApiBundle\Handler\JournalHandler
    ojs_api.journal.class: Ojs\JournalBundle\Entity\Journal
    ojs_api.publisher.handler.class: Ojs\ApiBundle\Handler\PublisherHandler
    ojs_api.publisher.class: Ojs\JournalBundle\Entity\Publisher
    ojs_api.institution.handler.class: Ojs\ApiBundle\Handler\InstitutionHandler
    ojs_api.institution.class: Ojs\JournalBundle\Entity\Institution
    ojs_api.subject.handler.class: Ojs\ApiBundle\Handler\SubjectHandler
    ojs_api.subject.class: Ojs\JournalBundle\Entity\Subject
    ojs_api.lang.handler.class: Ojs\ApiBundle\Handler\LangHandler
    ojs_api.lang.class: Ojs\JournalBundle\Entity\Lang
    ojs_api.index.handler.class: Ojs\ApiBundle\Handler\IndexHandler
    ojs_api.index.class: Ojs\JournalBundle\Entity\Index
    ojs_api.period.handler.class: Ojs\ApiBundle\Handler\PeriodHandler
    ojs_api.period.class: Ojs\JournalBundle\Entity\Period
    ojs_api.person_title.handler.class: Ojs\ApiBundle\Handler\PersonTitleHandler
    ojs_api.person_title.class: Ojs\JournalBundle\Entity\PersonTitle
    ojs_api.publisher_type.handler.class: Ojs\ApiBundle\Handler\PublisherTypeHandler
    ojs_api.publisher_type.class: Ojs\JournalBundle\Entity\PublisherTypes
    ojs_api.article_type.handler.class: Ojs\ApiBundle\Handler\ArticleTypeHandler
    ojs_api.article_type.class: Ojs\JournalBundle\Entity\ArticleTypes
    ojs_api.contact.handler.class: Ojs\ApiBundle\Handler\ContactHandler
    ojs_api.contact.class: Ojs\JournalBundle\Entity\JournalContact

services:
    ojs_api.contact_type.handler:
        class: %ojs_api.contact_type.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.contact_type.class%', '@form.factory']
    ojs_api.journal.handler:
        class: %ojs_api.journal.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.journal.class%', '@form.factory']
    ojs_api.publisher.handler:
        class: %ojs_api.publisher.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.publisher.class%', '@form.factory']
    ojs_api.institution.handler:
        class: %ojs_api.institution.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.institution.class%', '@form.factory']
    ojs_api.subject.handler:
        class: %ojs_api.subject.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.subject.class%', '@form.factory']
    ojs_api.lang.handler:
        class: %ojs_api.lang.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.lang.class%', '@form.factory']
    ojs_api.index.handler:
        class: %ojs_api.index.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.index.class%', '@form.factory']
    ojs_api.period.handler:
        class: %ojs_api.period.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.period.class%', '@form.factory']
    ojs_api.person_title.handler:
        class: %ojs_api.person_title.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.person_title.class%', '@form.factory']
    ojs_api.publisher_type.handler:
        class: %ojs_api.publisher_type.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.publisher_type.class%', '@form.factory']
    ojs_api.article_type.handler:
        class: %ojs_api.article_type.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.article_type.class%', '@form.factory']
    ojs_api.contact.handler:
        class: %ojs_api.contact.handler.class%
        arguments: ['@doctrine.orm.entity_manager', '%ojs_api.contact.class%', '@form.factory']
