Ojs\CmsBundle\Entity\Announcement:
    table: announcement
    type: entity
    repositoryClass: Ojs\CmsBundle\Entity\AnnouncementRepository
    inheritanceType: SINGLE_TABLE
    cache:
        usage: NONSTRICT_READ_WRITE
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        admin: Ojs\AdminBundle\Entity\AdminAnnouncement
        journal: Ojs\JournalBundle\Entity\JournalAnnouncement
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        image:
            type: string
            length: 255
            nullable: true
        content:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
