Ojs\CmsBundle\Entity\FileTranslation:
    type: entity
    table: file_translations
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255