Ojs\CmsBundle\Entity\Post:
  type: entity
  repositoryClass: Ojs\CmsBundle\Entity\PostRepository
  table: posts
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
      name: discriminator
      type: string
  discriminatorMap:
      admin: Ojs\AdminBundle\Entity\AdminPost
      journal: Ojs\JournalBundle\Entity\JournalPost
  gedmo:
    soft_deleteable:
      field_name: deletedAt
    loggable: true
  id:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  oneToMany:
    translations:
      targetEntity: Ojs\CmsBundle\Entity\PostTranslation
      mappedBy: translatable
  fields:
    slug:
      type: string
      gedmo:
        slug:
          seperator: "-"
          fields:
            - id
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
      nullable: false
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
    deletedAt:
      type: datetime
      nullable: true