Ojs\JournalBundle\Entity\InstitutionTranslation:
  properties:

Ojs\JournalBundle\Entity\Institution:
    properties:
        translations:
            - Valid: ~
        name:
          - NotBlank: ~
        slug:
          - NotBlank: ~
        address:
          - NotBlank: ~
        phone:
          - NotBlank: ~
        email:
          - NotBlank: ~
          - Email: ~
