Ojs\JournalBundle\Entity\InstitutionTypesTranslation:
  properties:
    name:
      - NotBlank: ~

Ojs\JournalBundle\Entity\InstitutionTypes:
    properties:
        translations:
            - Valid: ~
