journal_publisher_hosting:
    path:  /
    defaults: { _controller: "OjsSiteBundle:Hosting:index" }

journal_hosting_archive:
    path:  /archive
    defaults: { _controller: "OjsSiteBundle:Hosting:archiveIndex", isJournalHosting: true }

publisher_hosting_journal_index:
    path:  /{slug}
    defaults: { _controller: "OjsSiteBundle:Hosting:journalIndex", slug: null}

publisher_hosting_journal_issue:
    path: /{journal_slug}/issue/{id}
    defaults: { _controller: "OjsSiteBundle:Hosting:issuePage"}

journal_hosting_issue:
    path: /issue/{id}
    defaults: { _controller: "OjsSiteBundle:Hosting:issuePage", isJournalHosting: true}

publisher_hosting_journal_issue_article:
    path:  /{slug}/issue/{issue_id}/{article_id}
    defaults: { _controller: "OjsSiteBundle:Hosting:articlePage", issue_id: null}

journal_hosting_issue_article:
    path:  /issue/{issue_id}/{article_id}
    defaults: { _controller: "OjsSiteBundle:Hosting:articlePage", [issue_id: null, isJournalHosting: true]}

publisher_hosting_journal_archive:
    path:  /{slug}/archive
    defaults: { _controller: "OjsSiteBundle:Hosting:archiveIndex" }

