journal_publisher_hosting:
    path:  /
    defaults: { _controller: "OjsSiteBundle:Hosting:index" }

journal_hosting_archive:
    path:  /archive
    defaults: { _controller: "OjsSiteBundle:Hosting:archiveIndex", isJournalHosting: true }

journal_hosting_issue:
    path: /issue/{id}
    defaults: { _controller: "OjsSiteBundle:Hosting:issuePage", [id: null, isJournalHosting: true]}

journal_hosting_issue_article:
    path:  /issue/{issue_id}/{article_id}
    defaults: { _controller: "OjsSiteBundle:Hosting:articlePage", [issue_id: null, isJournalHosting: true]}

