#RSS
ojs_index_sitemap:
  path: /
  host: %base_host%
  defaults: {_controller: OjsSiteBundle:Sitemap:index }
ojs_journals_sitemap:
  path: /journals.{_format}
  host: "{publisher}.%base_host%"
  defaults: { _controller: OjsSiteBundle:Sitemap:journals }
ojs_subjects_sitemap:
  path: /subjects.{_format}
  host: "{publisher}.%base_host%"
  defaults: { _controller: OjsSiteBundle:Sitemap:subjects, publisher: 'www' }
ojs_subjects_sitemap_:
  path: /subjects.{_format}
  defaults: { _controller: OjsSiteBundle:Sitemap:subjects }
ojs_subject_sitemap:
  path: /subject/{subject}.{_format}
  host: "{publisher}.%base_host%"
  defaults: { _controller: OjsSiteBundle:Sitemap:subject }
ojs_subject_sitemap_:
  path: /subject/{subject}.{_format}
  host: %base_host%
  defaults: { _controller: OjsSiteBundle:Sitemap:subject , publisher: 'www'}

ojs_journal_sitemap:
  path: /{journal}.{_format}
  host: "{publisher}.%base_host%"
  defaults: { _controller: OjsSiteBundle:Sitemap:journal }
ojs_journal_detail_sitemap:
  path: /{journal}/detail.{_format}
  host: "{publisher}.%base_host%"
  defaults: { _controller: OjsSiteBundle:Sitemap:journalDetail }
ojs_articles_sitemap:
  path: /{journal}/articles.{_format}
  host: "{publisher}.%base_host%"
  defaults: { _controller: OjsSiteBundle:Sitemap:article }
ojs_last_issue_sitemap:
  path: /{journal}/last.{_format}
  host: "{publisher}.%base_host%"
  defaults: { _controller: OjsSiteBundle:Sitemap:lastIssue }
ojs_issues_sitemap:
  path: /{journal}/issues.{_format}
  host: "{publisher}.%base_host%"
  defaults: {_controller: OjsSiteBundle:Sitemap:issues }
ojs_publishers_sitemap:
  path: /publishers.{_format}
  host: %base_host%
  defaults: { _controller: OjsSiteBundle:Sitemap:publishers }

ojs_static_sitemap:
  path: /static.{_format}
  host: %base_host%
  defaults: { _controller: OjsSiteBundle:Sitemap:static }

ojs_publisher_sitemap:
  path: /
  host: "{publisher}.%base_host%"
  defaults: {_controller: OjsSiteBundle:Sitemap:publisher }
