services:
  admin.event_listener:
    class: Ojs\AdminBundle\EventListener\AdminEventListener
    arguments: ["@router", "@doctrine.orm.entity_manager", "@ojs_mailer"]
    tags:
      - { name: kernel.event_subscriber }
