services:
  admin.event_listener:
    class: Ojs\AdminBundle\EventListener\AdminEventListener
    arguments: ["@router", "@doctrine.orm.entity_manager", "@ojs_mailer"]
    tags:
      - { name: kernel.event_subscriber }

  ojs.graph.data.generator:
    class: Ojs\AnalyticsBundle\Utils\GraphDataGenerator
    arguments: ["@doctrine.orm.entity_manager"]

  form.type.journal_application:
    class: Ojs\AdminBundle\Form\Type\JournalApplicationType
    tags:
      -
        alias: ojs_journalbundle_journalapplication
        name: form.type