services:
  admin.event_listener:
    class: Ojs\AdminBundle\EventListener\AdminEventListener
    arguments: ["@router", "@mailer", "@doctrine.orm.entity_manager", "%system_email%", "OJS SYSTEM"]
    tags:
      - { name: kernel.event_subscriber }